# Generated by Django 5.0.7 on 2024-09-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_usuarios', '0005_remove_usuario_correo_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
