# Generated by Django 4.2 on 2024-10-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_usuarios', '0006_alter_usuario_documento_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
    ]
