# Generated by Django 5.0.7 on 2024-09-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_productos', '0006_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
