# Generated by Django 4.2 on 2024-08-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_presentacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='cantidad_Stock',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='unidades_Paquete',
        ),
    ]
