# Generated by Django 4.0 on 2024-10-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_presentacion', '0002_remove_presentacion_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
