# Generated by Django 4.2 on 2024-09-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='producto',
        ),
    ]
