# Generated by Django 4.2 on 2024-09-19 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionar_proveedor', '0002_remove_proveedor_producto'),
        ('gestionar_productos', '0006_alter_producto_proveedor'),
        ('gestionar_compra', '0002_alter_compra_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad_Producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_Compra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor_Id',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_Compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad_productos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Compra_has_producto',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestionar_compra.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_proveedor.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
