# Generated by Django 5.0.7 on 2024-09-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_compra', '0003_detallecompra_remove_compra_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='proveedor',
        ),
    ]
