# Generated by Django 5.0.7 on 2024-08-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_ventas', '0002_alter_venta_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_Cierre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='saldo_Actual',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='saldo_Inicial',
        ),
    ]
