# Generated by Django 4.2 on 2024-09-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_ventas', '0007_detalleventa_remove_venta_cantidad_venta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='Producto',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
