# Generated by Django 4.0 on 2024-10-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_usuarios', '0006_alter_usuario_documento_alter_usuario_telefono'),
        ('gestionar_ventas', '0008_rename_producto_detalleventa_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_usuarios.usuario'),
        ),
    ]
